# check if postgres.type is set to external operator
{{ $is_operator := (eq .Values.postgres.type "operator") }}
{{ $is_external := (eq .Values.postgres.type "external") }}
{{ if not (or $is_operator  $is_external) }}
  {{- fail "Deploymnent FAILED, unknown postgres.type defined, please set postgres.type to operator or external ..." }}
{{ end }}

{{ $rabbitmq_enabled := .Values.rabbitmq.enabled }}
{{ $redis_enabled := .Values.redis.enabled }}
{{ if (and $rabbitmq_enabled  $redis_enabled) }}
  {{- fail "Deploymnent FAILED, cannot have both rabbitmq and redis enabled at the same time, check if you want to run geonode 5.0.0 or above (redis) or below (rabbitmq) ..." }}
{{ end }}

# geonode stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "geonode_pod_name" . }}"
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      org.geonode.instance: "{{ include "geonode_pod_name" . }}"
  serviceName: "{{ include "geonode_pod_name" . }}"
  replicas: {{ .Values.geonode.replicaCount }}
  template:
    metadata:
      labels:
        org.geonode.instance: "{{ include "geonode_pod_name" . }}"
      annotations:
        checksum/geonode-env: {{ include (print $.Template.BasePath "/geonode/geonode-env.yaml") . | sha256sum }}
        checksum/geonode-secret: {{ include (print $.Template.BasePath "/geonode/geonode-secret.yaml") . | sha256sum }}
        checksum/geonode-tasks-py: {{ include (print $.Template.BasePath "/geonode/geonode-tasks-py-conf.yaml") . | sha256sum }}
        checksum/geonode-settings-additions: {{ include (print $.Template.BasePath "/geonode/geonode-settings-additions.yaml") . | sha256sum }}
        checksum/geonode-uwsig: {{ include (print $.Template.BasePath "/geonode/geonode-uwsgi-ini-conf.yaml") . | sha256sum }}
    spec:
{{- $gnctx := default dict .Values.geonode.securityContext }}
      securityContext:
        runAsNonRoot: true
        fsGroup: {{- if hasKey $gnctx "fsGroup" }} {{ $gnctx.fsGroup }} {{- else }} {{ .Values.global.securityContext.fsGroup }} {{- end }}
        fsGroupChangePolicy: OnRootMismatch
      terminationGracePeriodSeconds: 3
{{- if not (empty .Values.geonode.imagePullSecret) }}
      imagePullSecrets:
      - name: {{ .Values.geonode.imagePullSecret }}
{{ end }}

      initContainers:
      # Wait for Postgres and rabbit
      - name: {{ .Values.geonode.init.container_name }}
        securityContext:
          runAsUser: {{- if hasKey $gnctx "runAsUser" }} {{ $gnctx.runAsUser }} {{- else }} {{ .Values.global.securityContext.runAsUser }} {{- end }}
          runAsGroup: {{- if hasKey $gnctx "runAsGroup" }} {{ $gnctx.runAsGroup }} {{- else }} {{ .Values.global.securityContext.runAsGroup }} {{- end }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        image: "{{ .Values.geonode.init.image.name }}:{{ .Values.geonode.init.image.tag }}"
        imagePullPolicy: {{ .Values.geonode.init.imagePullPolicy }}
        args:
        - -timeout=60s
        - -wait
        - tcp://{{ include "database_hostname" . }}:{{ include "database_port" . }}
        {{ if $rabbitmq_enabled }}
        - -wait
        - tcp://{{ include "rabbit_host" .}}
        {{ end }}
        {{ if $redis_enabled }}
        - -wait
        - tcp://{{ include "redis_host" . }}
        {{ end }}
      - name: seed-home
        image: "{{ .Values.geonode.image.name }}:{{ .Values.geonode.image.tag }}"
        imagePullPolicy: {{ .Values.geonode.imagePullPolicy }}
        command: ["sh", "-c"]
        args:
          - |
            cp -r /home/ubuntu/. /seed-geonode/
            cp -r /home/ubuntu/. /seed-celery/
        securityContext:
          runAsUser: {{- if hasKey $gnctx "runAsUser" }} {{ $gnctx.runAsUser }} {{- else }} {{ .Values.global.securityContext.runAsUser }} {{- end }}
          runAsGroup: {{- if hasKey $gnctx "runAsGroup" }} {{ $gnctx.runAsGroup }} {{- else }} {{ .Values.global.securityContext.runAsGroup }} {{- end }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: home-geonode
            mountPath: /seed-geonode
          - name: home-celery
            mountPath: /seed-celery

      containers:
      # This is the django app server
      - name: {{ .Values.geonode.container_name }}
        securityContext:
          runAsUser: {{- if hasKey $gnctx "runAsUser" }} {{ $gnctx.runAsUser }} {{- else }} {{ .Values.global.securityContext.runAsUser }} {{- end }}
          runAsGroup: {{- if hasKey $gnctx "runAsGroup" }} {{ $gnctx.runAsGroup }} {{- else }} {{ .Values.global.securityContext.runAsGroup }} {{- end }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        image: "{{ .Values.geonode.image.name }}:{{ .Values.geonode.image.tag }}"
        imagePullPolicy: {{ .Values.geonode.imagePullPolicy }}
        command:
        - bash
        - -c
        - |
          # execute prescript if defined
          {{ if .Values.geonode.tasks_pre_script }}
          invoke prescript
          {{ end }}

          # Setup
          {{ include "geonode_root_path" .}}/entrypoint.sh uwsgi --ini {{ include "geonode_root_path" .}}/uwsgi.ini

        ports:
        - name: http
          containerPort: 8000
        envFrom:
        - configMapRef:
            name: {{ include "geonode_pod_name" . }}-env
        - secretRef:
            name: {{ .Values.geonode.secret.existingSecretName | default (include "geonode_secret_name" .) | quote }}
        - secretRef:
            name: {{ .Values.geoserver.secret.existingSecretName | default (include "geoserver_secret_name" .) | quote }}

        env:
        - name: GEONODE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_geonode_password_secret_key_ref" . }}
              key: {{ include "database_geonode_password_key_ref" . }}
        - name: GEONODE_GEODATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_geodata_password_secret_key_ref" . }}
              key: {{ include "database_geodata_password_key_ref" . }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_postgres_password_secret_key_ref" . }}
              key: {{ include "database_postgres_password_key_ref" . }}
        - name: GEODATABASE_URL
          value: "postgis://$(GEONODE_GEODATABASE):$(GEONODE_GEODATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(GEONODE_GEODATABASE)"
        - name: DATABASE_URL
          value: "postgis://$(GEONODE_DATABASE):$(GEONODE_DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(GEONODE_DATABASE)"
        - name: PYTHONPATH
          value: "/opt/geonode-custom"

        volumeMounts:
        - name: pvc-statics
          mountPath: /mnt/volumes/statics
        - name: pvc-geoserver-data
          mountPath: /geoserver_data/data
        - name: pvc-backup-restore
          mountPath: /backup_restore
        - name: pvc-data
          mountPath: /data
        - name: cache-volume
          mountPath: /tmp
        - name: home-geonode
          mountPath: /home/ubuntu
        - name: tasks-py
          mountPath: "{{ include "geonode_root_path" .}}/tasks.py"
          subPath: tasks.py
          readOnly: true
        - name: entrypoint-sh
          mountPath: "{{ include "geonode_root_path" .}}/entrypoint.sh"
          subPath: entrypoint.sh
        - name: uwsgi-ini
          mountPath: "{{ include "geonode_root_path" .}}/uwsgi.ini"
          subPath: uwsgi.ini
          readOnly: true
        - name: settings-wrapper
          mountPath: /opt/geonode-custom/settings_wrapper.py
          subPath: settings_wrapper.py
          readOnly: true
        - name: settings-additions
          mountPath: /opt/geonode-custom/settings_additions.py
          subPath: settings_additions.py
          readOnly: true
        {{ if .Values.geonodeFixtures }}
        - name: geonode-fixtures
          mountPath: "{{ include "geonode_path" .}}/fixtures"
          readOnly: true
        {{ end }}

        startupProbe:
          {{- toYaml $.Values.geonode.startupProbe | nindent 10 }}
        livenessProbe:
          {{- toYaml $.Values.geonode.livenessProbe | nindent 10 }}
        resources:
          {{- toYaml $.Values.geonode.resources | nindent 10 }}


      # Celery is the task worker
      - name: {{ .Values.geonode.celery.container_name }}
        securityContext:
          runAsUser: {{- if hasKey $gnctx "runAsUser" }} {{ $gnctx.runAsUser }} {{- else }} {{ .Values.global.securityContext.runAsUser }} {{- end }}
          runAsGroup: {{- if hasKey $gnctx "runAsGroup" }} {{ $gnctx.runAsGroup }} {{- else }} {{ .Values.global.securityContext.runAsGroup }} {{- end }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        image: "{{ .Values.geonode.image.name }}:{{ .Values.geonode.image.tag }}"
        imagePullPolicy: {{ .Values.geonode.celery.imagePullPolicy }}
        command:
        - bash
        - -c
        - |
          {{ if .Values.geonode.sentry.enabled }}
          pip install sentry-sdk
          {{ end }}

          set -e
          echo "Starting celery-cmd..."

          # Setup
          exec {{ include "geonode_root_path" .}}/entrypoint.sh celery-cmd

        envFrom:
        - configMapRef:
            name: {{ include "geonode_pod_name" . }}-env
        - secretRef:
            name: {{ .Values.geonode.secret.existingSecretName | default (include "geonode_secret_name" .) | quote }}
        - secretRef:
            name: {{ .Values.geoserver.secret.existingSecretName | default (include "geoserver_secret_name" .) | quote }}

        env:
        - name: IS_CELERY
          value: 'True'
        # Override Celery Log file location as defined in "celery-cmd". Container should write to stdout, not files.
        - name: CELERY__LOG_FILE
          value: "/dev/stdout"
        - name: CELERY__BEAT_LOG
          value: "/dev/stdout"
        - name: CELERY__LOG_LEVEL
          value: "INFO"
        - name: INVOKE_LOG_STDOUT
          value: "True"
        #
        - name: GEONODE_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_geonode_password_secret_key_ref" . }}
              key: {{ include "database_geonode_password_key_ref" . }}
        - name: GEONODE_GEODATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_geodata_password_secret_key_ref" . }}
              key: {{ include "database_geodata_password_key_ref" . }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "database_postgres_password_secret_key_ref" . }}
              key: {{ include "database_postgres_password_key_ref" . }}
        - name: GEODATABASE_URL
          value: "postgis://$(GEONODE_GEODATABASE):$(GEONODE_GEODATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(GEONODE_GEODATABASE)"
        - name: DATABASE_URL
          value: "postgis://$(GEONODE_DATABASE):$(GEONODE_DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(GEONODE_DATABASE)"
        #
        - name: PYTHONPATH
          value: "/opt/geonode-custom"

        ports:
        - containerPort: 5555

        volumeMounts:
        - name: pvc-statics
          mountPath: /mnt/volumes/statics
        - name: pvc-geoserver-data
          mountPath: /geoserver_data/data
        - name: pvc-backup-restore
          mountPath: /backup_restore
        - name: pvc-data
          mountPath: /data
        - name: cache-volume
          mountPath: /tmp
        - name: home-celery
          mountPath: /home/ubuntu
        - name: entrypoint-sh
          mountPath: "{{ include "geonode_root_path" .}}/entrypoint.sh"
          subPath: entrypoint.sh
        - name: tasks-py
          mountPath: "{{ include "geonode_root_path" .}}/tasks.py"
          subPath: tasks.py
          readOnly: true
        - name: settings-wrapper
          mountPath: /opt/geonode-custom/settings_wrapper.py
          subPath: settings_wrapper.py
          readOnly: true
        - name: settings-additions
          mountPath: /opt/geonode-custom/settings_additions.py
          subPath: settings_additions.py
          readOnly: true
        {{ if .Values.geonodeFixtures }}
        - name: geonode-fixtures
          mountPath: "{{ include "geonode_path" .}}/fixtures"
          readOnly: true
        {{ end }}

        resources:
          requests:
            memory: {{ .Values.geonode.celery.resources.requests.memory }}
            cpu: {{ .Values.geonode.celery.resources.requests.cpu }}
          limits:
            memory: {{ .Values.geonode.celery.resources.limits.memory }}
            cpu: {{ .Values.geonode.celery.resources.limits.cpu }}

      volumes:
        - name: pvc-statics
          persistentVolumeClaim:
            claimName: {{ include "pvc_statics_name" . }}
        - name: pvc-geoserver-data
          persistentVolumeClaim:
            claimName: {{ include "pvc_geoserver_data_name" . }}
        - name: pvc-backup-restore
          persistentVolumeClaim:
            claimName: {{ include "pvc_backup_restore_name" . }}
        - name: pvc-data
          persistentVolumeClaim:
            claimName: {{ include "pvc_data_name" . }}
        - name: tasks-py
          configMap:
            name: {{ .Release.Name }}-geonode-tasks-py
            items:
            - key: tasks.py
              path: "tasks.py"
        - name: entrypoint-sh
          configMap:
            name: {{ .Release.Name }}-geonode-entrypoint-sh
            defaultMode: 0555
            items:
            - key: entrypoint.sh
              path: "entrypoint.sh"
        - name: uwsgi-ini
          configMap:
            name: {{ .Release.Name }}-geonode-uwsgi-ini
            defaultMode: 0555
            items:
            - key: uwsgi.ini
              path: "uwsgi.ini"
        - name: settings-wrapper
          configMap:
            name: {{ .Release.Name }}-geonode-settings-wrapper
            defaultMode: 0555
        - name: settings-additions
          configMap:
            name: {{ .Release.Name }}-geonode-settings-additions
            defaultMode: 0555
        {{- if .Values.geonodeFixtures }}
        - name: geonode-fixtures
          configMap:
            name: {{ .Release.Name }}-geonode-fixtures
            defaultMode: 0555
            items:
            {{- range $key, $value := .Values.geonodeFixtures }}
            - key: {{ $key | quote }}
              path: {{ $key | quote }}
            {{- end }}
        {{- end }}
        # Using an emptyDir to cache compiled statics... it will survive container crashes, but not pod restarts
        - name: cache-volume
          emptyDir: {}
        - name: home-geonode
          emptyDir: {}
        - name: home-celery
          emptyDir: {}

